#ifndef LIBIMAGERESIZER_GLOBAL_H
#define LIBIMAGERESIZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBIMAGERESIZER_LIBRARY)
#  define LIBIMAGERESIZERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBIMAGERESIZERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBIMAGERESIZER_GLOBAL_H
